name: Build
on: [push]

jobs:
  Test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          bundle install
      - name: Run tests
        run: fastlane test
