name: Docs
on:
  push:
    branches:
      - master
      - feature/gh-actions

jobs:
  Generate:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
          bundle update --bundler
          bundle install
      - name: Publish
        run: ./.scripts/update-gh-pages
